// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/(public)/home/home_page.dart' as a1;
import 'app/(public)/home/todos_details/todos_details_page.dart' as a0;
import 'app/(public)/login/login_page.dart' as a3;
import 'app/(public)/splash/splash_page.dart' as a2;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home/todos_details',
        uri: Uri.parse('/home/todos_details'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.TodosDetailsPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/',
        uri: Uri.parse('/'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.SplashPage(),
        ),
      ),
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.LoginPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  home: (
    path: '/home',
    todosDetails: '/home/todos_details',
  ),
  splash: '/',
  login: '/login',
);
